/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nativeLib_NativeLib */

#ifndef _Included_nativeLib_NativeLib
#define _Included_nativeLib_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nativeLib_NativeLib
 * Method:    generatePass
 * Signature: ([Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_nativeLib_NativeLib_generatePass
  (JNIEnv *, jclass, jobjectArray, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
